// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

UserModel _$UserModelFromJson(Map<String, dynamic> json) => UserModel(
      userTpCd: json['userTpCd'] as String,
      userNm: json['userNm'] as String,
      userId: json['userId'] as String,
      joinDay: json['joinDay'] as String,
      bankAccount: json['bankAccount'] as String,
      accountNumber: json['accountNumber'] as String,
      birthDay: json['birthDay'] as String,
      genderCd: json['genderCd'] as String,
      hpNum: json['hpNum'] as String,
      email: json['email'] as String,
      emailVerfYn: json['emailVerfYn'] as String,
      jobCd: json['jobCd'] as String,
      asignJobCd: json['asignJobCd'] as String,
      wedTpCd: json['wedTpCd'] as String,
      housTpCd: json['housTpCd'] as String,
      petYn: json['petYn'] as String,
      petTpCd: json['petTpCd'] as String,
      petNm: json['petNm'] as String,
      occpSidoCd: json['occpSidoCd'] as String,
      occpSigunguCd: json['occpSigunguCd'] as String,
      intvSidoCd: json['intvSidoCd'] as String,
      intvSigunguCd: json['intvSigunguCd'] as String,
      oflIntvRwdTpCd: json['oflIntvRwdTpCd'] as String,
      onlIntvRwdTpCd: json['onlIntvRwdTpCd'] as String,
      mainUseOnlSvcCn: json['mainUseOnlSvcCn'] as String,
      hobySubs: json['hobySubs'] as String,
      rcmdUserCd: json['rcmdUserCd'] as String,
      isAgreeYn: json['isAgreeYn'] as String,
      isAgreeDt: json['isAgreeDt'] as String,
      empYn: json['empYn'] as String,
      empNo: json['empNo'] as String,
      delYn: json['delYn'] as String,
      frstRegtDt: json['frstRegtDt'] as String,
      finlUpdtDt: json['finlUpdtDt'] as String,
    );

Map<String, dynamic> _$UserModelToJson(UserModel instance) => <String, dynamic>{
      'userTpCd': instance.userTpCd,
      'userNm': instance.userNm,
      'userId': instance.userId,
      'joinDay': instance.joinDay,
      'bankAccount': instance.bankAccount,
      'accountNumber': instance.accountNumber,
      'birthDay': instance.birthDay,
      'genderCd': instance.genderCd,
      'hpNum': instance.hpNum,
      'email': instance.email,
      'emailVerfYn': instance.emailVerfYn,
      'jobCd': instance.jobCd,
      'asignJobCd': instance.asignJobCd,
      'wedTpCd': instance.wedTpCd,
      'housTpCd': instance.housTpCd,
      'petYn': instance.petYn,
      'petTpCd': instance.petTpCd,
      'petNm': instance.petNm,
      'occpSidoCd': instance.occpSidoCd,
      'occpSigunguCd': instance.occpSigunguCd,
      'intvSidoCd': instance.intvSidoCd,
      'intvSigunguCd': instance.intvSigunguCd,
      'oflIntvRwdTpCd': instance.oflIntvRwdTpCd,
      'onlIntvRwdTpCd': instance.onlIntvRwdTpCd,
      'mainUseOnlSvcCn': instance.mainUseOnlSvcCn,
      'hobySubs': instance.hobySubs,
      'rcmdUserCd': instance.rcmdUserCd,
      'isAgreeYn': instance.isAgreeYn,
      'isAgreeDt': instance.isAgreeDt,
      'empYn': instance.empYn,
      'empNo': instance.empNo,
      'delYn': instance.delYn,
      'frstRegtDt': instance.frstRegtDt,
      'finlUpdtDt': instance.finlUpdtDt,
    };
